const CAREER_KEY='careerData';
const emptyCareer=()=>({ladder:'',trainings:[],societies:[],association:{status:'',prefecture:''},certifications:[],learningGoals:''});
const loadCareer=()=>{try{return {...emptyCareer(),...JSON.parse(localStorage.getItem(CAREER_KEY)||'{}')}}catch{return emptyCareer()}};
const esc=value=>String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function itemTemplate(kind,item={}){const society=kind==='society', cert=kind==='certification';return `<div class="career-repeat-item" data-kind="${kind}"><label>${society?'加入している学会名':cert?'資格・認定名':'研修・セミナー名'}<input name="name" value="${esc(item.name)}"></label><label>${society?'入会年月':cert?'取得年月':'開催日'}<input name="date" type="${society||cert?'month':'date'}" value="${esc(item.date)}"></label>${kind==='training'?`<label>主催者<input name="organizer" value="${esc(item.organizer)}"></label>`:''}${cert?`<label>更新年月<input name="renewal" type="month" value="${esc(item.renewal)}"></label>`:''}<label>${kind==='training'?'学んだこと・メモ':'メモ'}<textarea name="note" rows="3">${esc(item.note)}</textarea></label><button class="remove-button" type="button">この項目を削除</button></div>`}
function addItem(kind,item){document.querySelector(`#${kind}-list`).insertAdjacentHTML('beforeend',itemTemplate(kind,item))}
function readItems(kind){return [...document.querySelectorAll(`#${kind}-list .career-repeat-item`)].map(node=>Object.fromEntries([...node.querySelectorAll('input,textarea')].map(input=>[input.name,input.value])))}
function renderSummary(data){const rows=[['現在のラダー',data.ladder],['最近参加した研修',data.trainings.map(x=>x.name).filter(Boolean).join('、')],['加入している学会',data.societies.map(x=>x.name).filter(Boolean).join('、')],['資格・認定',data.certifications.map(x=>x.name).filter(Boolean).join('、')],['これから学びたいこと',data.learningGoals]];document.querySelector('#career-summary-cards').innerHTML=rows.map(([title,body])=>`<article class="career-summary-card"><h3>${title}</h3><p>${esc(body||'まだ記録されていません').replace(/\n/g,'<br>')}</p></article>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{const data=loadCareer();document.querySelector('#ladder').value=data.ladder;document.querySelector('#association-status').value=data.association.status;document.querySelector('#association-prefecture').value=data.association.prefecture;document.querySelector('#learning-goals').value=data.learningGoals;[['training',data.trainings],['society',data.societies],['certification',data.certifications]].forEach(([kind,items])=>(items.length?items:[{}]).forEach(item=>addItem(kind,item)));['training','society','certification'].forEach(kind=>document.querySelector(`#add-${kind}`).addEventListener('click',()=>addItem(kind,{})));document.querySelector('#career-form').addEventListener('click',e=>{if(e.target.classList.contains('remove-button'))e.target.closest('.career-repeat-item').remove()});document.querySelector('#career-form').addEventListener('submit',e=>{e.preventDefault();const saved={ladder:document.querySelector('#ladder').value,trainings:readItems('training'),societies:readItems('society'),association:{status:document.querySelector('#association-status').value,prefecture:document.querySelector('#association-prefecture').value},certifications:readItems('certification'),learningGoals:document.querySelector('#learning-goals').value};localStorage.setItem(CAREER_KEY,JSON.stringify(saved));document.querySelector('#career-status').textContent='保存しました。';renderSummary(saved)});renderSummary(data)});
