(function () {
  'use strict';
  const KEY = 'kosodateNurseSchedules', pad = n => String(n).padStart(2, '0');
  const today = new Date(); let fiscalYear = today.getMonth() < 3 ? today.getFullYear() - 1 : today.getFullYear(); let view = today.getMonth() >= 3 && today.getMonth() < 9 ? 'first' : 'second'; let selectedDate;
  const keyOf = d => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  const dateOf = key => { const [y, m, d] = key.split('-').map(Number); return new Date(y, m - 1, d); };
  const formatDate = key => { const d = dateOf(key); return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`; };
  function getSchedules() { try { return JSON.parse(localStorage.getItem(KEY) || '[]'); } catch { return []; } }
  function saveSchedules(items) { localStorage.setItem(KEY, JSON.stringify(items)); }
  function getSchedulesByDate(date) { return getSchedules().filter(item => item.date === date); }
  function saveSchedule(item) { const all = getSchedules(), index = all.findIndex(saved => saved.id === item.id); if (index < 0) all.push(item); else all[index] = item; saveSchedules(all); }
  function deleteSchedule(id) { saveSchedules(getSchedules().filter(item => item.id !== id)); }
  function months() { return view === 'first' ? [4, 5, 6, 7, 8, 9] : view === 'second' ? [10, 11, 12, 1, 2, 3] : [4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3]; }
  const monthYear = m => m <= 3 ? fiscalYear + 1 : fiscalYear;
  function renderScheduleCalendar() {
    document.querySelector('#fiscal-year-label').textContent = `${fiscalYear}年度`; document.querySelector('#schedule-period').textContent = view === 'first' ? '前期：4月〜9月' : view === 'second' ? '後期：10月〜翌年3月' : '年間：4月〜翌年3月';
    const root = document.querySelector('#schedule-months'); root.className = `schedule-months is-${view}`; root.innerHTML = '';
    months().forEach(month => { const year = monthYear(month), first = new Date(year, month - 1, 1), last = new Date(year, month, 0), box = document.createElement('section'); box.className = 'schedule-month'; box.innerHTML = `<h2>${month}月</h2><div class="schedule-weekdays"><span>日</span><span>月</span><span>火</span><span>水</span><span>木</span><span>金</span><span>土</span></div><div class="schedule-days"></div>`; const days = box.querySelector('.schedule-days'); for (let i = 0; i < first.getDay(); i++) days.append(document.createElement('span')); for (let day = 1; day <= last.getDate(); day++) { const d = new Date(year, month - 1, day), key = keyOf(d), button = document.createElement('button'); button.type = 'button'; button.className = 'schedule-day'; button.textContent = day; button.setAttribute('aria-label', formatDate(key)); if (key === keyOf(today)) button.classList.add('is-today'); if (getSchedulesByDate(key).length) button.classList.add('has-schedule'); button.addEventListener('click', () => selectDate(key)); days.append(button); } root.append(box); });
  }
  function resetForm() { document.querySelector('#schedule-form').reset(); document.querySelector('#schedule-id').value = ''; document.querySelector('#schedule-cancel').hidden = true; }
  function selectDate(key) { selectedDate = key; document.querySelector('#schedule-editor').hidden = false; document.querySelector('#selected-date-heading').textContent = `${formatDate(key)}の予定`; resetForm(); renderList(); document.querySelector('#schedule-editor').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function renderList() { const root = document.querySelector('#schedule-list'), items = getSchedulesByDate(selectedDate); root.innerHTML = '<h3>この日の予定</h3>'; if (!items.length) { root.insertAdjacentHTML('beforeend', '<p class="schedule-empty">予定はまだありません。</p>'); return; } items.forEach(item => { const card = document.createElement('article'), time = item.startTime || item.endTime ? `${item.startTime || ''}〜${item.endTime || ''}` : '終日'; card.className = 'schedule-item'; card.innerHTML = `<div><span class="schedule-category">${item.category}</span><strong>${item.title}</strong><p>${time}${item.memo ? `　${item.memo}` : ''}</p></div><div class="schedule-item-actions"><button type="button" data-edit="${item.id}">編集</button><button type="button" data-delete="${item.id}">削除</button></div>`; root.append(card); }); root.querySelectorAll('[data-edit]').forEach(b => b.addEventListener('click', () => editSchedule(b.dataset.edit))); root.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => { deleteSchedule(b.dataset.delete); renderScheduleCalendar(); renderList(); })); }
  function editSchedule(id) { const item = getSchedules().find(saved => saved.id === id); if (!item) return; ['id','category','title','start','end','memo'].forEach(name => { const el = document.querySelector(`#schedule-${name}`); if (el) el.value = name === 'id' ? item.id : name === 'start' ? item.startTime : name === 'end' ? item.endTime : item[name]; }); document.querySelector('#schedule-cancel').hidden = false; document.querySelector('#schedule-title').focus(); }
  document.addEventListener('DOMContentLoaded', () => { renderScheduleCalendar(); document.querySelectorAll('[data-view]').forEach(tab => tab.addEventListener('click', () => { view = tab.dataset.view; document.querySelectorAll('[data-view]').forEach(t => t.setAttribute('aria-selected', t === tab)); renderScheduleCalendar(); })); document.querySelector('#previous-year').addEventListener('click', () => { fiscalYear--; renderScheduleCalendar(); }); document.querySelector('#next-year').addEventListener('click', () => { fiscalYear++; renderScheduleCalendar(); }); document.querySelector('#current-year-button').addEventListener('click', () => { const d = new Date(); fiscalYear = d.getMonth() < 3 ? d.getFullYear() - 1 : d.getFullYear(); view = d.getMonth() >= 3 && d.getMonth() < 9 ? 'first' : 'second'; document.querySelectorAll('[data-view]').forEach(t => t.setAttribute('aria-selected', t.dataset.view === view)); renderScheduleCalendar(); }); document.querySelector('#schedule-cancel').addEventListener('click', resetForm); document.querySelector('#schedule-form').addEventListener('submit', e => { e.preventDefault(); saveSchedule({ id: document.querySelector('#schedule-id').value || `schedule-${Date.now()}`, date: selectedDate, category: document.querySelector('#schedule-category').value, title: document.querySelector('#schedule-title').value.trim(), startTime: document.querySelector('#schedule-start').value, endTime: document.querySelector('#schedule-end').value, memo: document.querySelector('#schedule-memo').value.trim() }); resetForm(); renderScheduleCalendar(); renderList(); }); });
  window.ScheduleStore = { saveSchedule, getSchedulesByDate, deleteSchedule };
}());
